import 'package:doctorapp/shared/network/local/cach_helper.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:intl/intl.dart';

List<String> specialization = [
  'Allergy and immunology',
  'Anesthesiology',
  'Dermatology',
  'Diagnostic radiology',
  'Emergency medicine',
  'Family medicine',
  'Internal medicine',
  'Medical genetics',
  'Neurology',
  ' Nuclear medicine',
  'Obstetrics and gynecology',
  'Ophthalmology',
  ' Pathology',
  'Pediatrics',
  ' Physical medicine and rehabilitation',
  ' Preventive medicine',
  ' Psychiatry',
  'Radiation oncology',
  ' Surgery',
  'Urology',
];

List<String> countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  ' Angola',
  ' Antigua and Barbuda',
  'Argentina',
  ' Armenia',
  ' Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  '	Botswana',
  'Brazil',
  'Brunei',
  '	Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Côte d\'Ivoire	',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  '	Congo (Congo-Brazzaville)',
  '	Costa Rica',
  'Croatia',
  '	Cuba',
  'Cyprus',
  '	Czechia (Czech Republic)',
  'Democratic Republic of the Congo',
  '	Denmark',
  '	Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  '	Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini (fmr. "Swaziland")',
  'Ethiopia',
  'Fiji',
  'Finland',
  '	France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  '	Greece',
  'Grenada',
  'Guatemala',
  '	Guinea',
  'Guinea-Bissau',
  '	Guyana',
  '	Haiti',
  'Holy See',
  '	Honduras',
  'Hungary',
  'Iceland',
  '	India',
  'Indonesia',
  '	Iran',
  '	Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  '	Kazakhstan',
  'Kenya',
  'Kiribati',
  '	Kuwait',
  'Kyrgyzstan',
  '	Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  '	Liberia',
  '	Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  '	Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  '	Mauritius',
  'Mexico',
  '	Micronesia',
  '	Moldova',
  'Monaco',
  'Mongolia',
  '	Montenegro',
  '	Morocco',
  'Mozambique',
  'Myanmar (formerly Burma)',
  '	Namibia',
  '	Nauru',
  '	Nepal',
  '	Netherlands',
  'New Zealand',
  '	Nicaragua',
  '	Niger',
  '	Nigeria',
  'North Korea',
  '	North Macedonia',
  '	Norway',
  '	Oman',
  '	Pakistan',
  '	Palau',
  '	Palestine State',
  'Panama',
  '	Papua New Guinea',
  '	Paraguay',
  '	Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  '	Romania',
  '	Russia',
  '	Rwanda',
  'Saint Kitts and Nevis',
  '	Saint Lucia',
  '	Saint Vincent and the Grenadines',
  '	Samoa',
  'San Marino',
  'Sao Tome and Principe',
  '	Saudi Arabia',
  '	Senegal',
  '	Serbia',
  '	Seychelles',
  'Sierra Leone',
  '	Singapore',
  'Slovakia',
  '	Slovenia',
  '	Solomon Islands',
  'Somalia',
  '	South Africa',
  '	South Korea',
  '	South Sudan',
  '	Spain',
  'Sri Lanka',
  '	Sudan',
  '	Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  '	Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  '	United Arab Emirates',
  'United Kingdom',
  'United States of America',
  '	Uruguay',
  '	Uzbekistan',
  '	Vanuatu',
  'Venezuela',
  'Vietnam',
  '	Yemen',
  'Zambia',
  '	Zimbabwe'
];
List < String > gender =['Male' , 'Female'];
List<String>  scientificDegree = [

  'Professional Certificate',
  'Undergraduate Degrees',
  'Transfer Degree',
  'Associate Degree',
  'Bachelor Degree',
  'Graduate Degrees'
  'Master Degree',
  'Doctoral Degree',
  'Professional Degree',
  'Specialist Degree',

    ];
List<String>  bloodTypes = [

'A+'	,'A-',
'B+','	B-',
'AB+'	,'AB-',
'O+','	O-',];


List<String>  chronicDiseases = [

 'ALS (Lou Gehrig\'s Disease) ',
'Alzheimer\'s Disease and other Dementias ',
  ' Arthritis ',
  'Asthma ',
  'Cancer ',
  ' Chronic Obstructive Pulmonary Disease (COPD) ',
  'Crohn\'s Disease, Ulcerative Colitis, Other Inflammatory Bowel Diseases, Irritable Bowel Syndrome ',
  'Cystic Fibrosis ',
  'Diabetes ',
  'Eating Disorders ',
  'Heart Disease ',
  ' Obesity ',
  'Oral Health ',
  'Osteoporosis ',
  'Reflex Sympathetic Dystrophy (RSD) Syndrome ',
  'Tobacco Use and Related Conditions ',
'Don\'t have'];

var uID =  FirebaseAuth.instance.currentUser?.uid;
var now = DateTime.now();
String formattedDate = DateFormat('yyyy-MM-dd  kk:mm').format(now);
//key of map
// AIzaSyDlt89VGiO9EmfZzYxtwyFs-oQH9X2Hzng

 const String apiKey = "AIzaSyDlt89VGiO9EmfZzYxtwyFs-oQH9X2Hzng";
